### DISCUSSION TITLE
Icon Tagging System

### DISCUSSION THREAD

**Discussion by moertel** [zixpo/candybar#224] [Ideas]
Each week I have a couple of users ask me about this because the icon search functionality is a bit limited. I started to give my icons really long and clumsy names trying to get tags and synonyms in ("Action Launcher House Home") but there should be a better way.

(We could potentially even crowdsource the tags, because if I draw the Action Launcher icon like a house, chances are you do too. ;))

**Comment by Donnnno** [comment]
One of the most requested features here too. We've built some things into Arcticons to create categories more easily, but that's only a partial solution.
We discovered that Google Play has categories for apps, and that it basically allows unlimited scraping for the Icon Request dashboard. Maybe those tags could be helpful for a database sort of thing?

**Reply by moertel** [reply]
That's a great use of categories! I hadn't even considered that. 😊

I'm not sure how open you are to this but instead of editing the XMLs directly, I built a different method into Retro Mode where I list out the icon names and component names. This gives me some extra flexibility for adding meta information. Currently it looks like this and there's a script that creates the XMLs in the specified locations:

```yaml
icon_google_voice_search.png:
  name: Google Voice Search
  categories: ["Google", "V"]
  mappings:
    - component: com.google.android.googlequicksearchbox/com.google.android.googlequicksearchbox.VoiceSearchActivity
```

With this approach, it would be easy to just add another `tags` key to the icon and end up with:
```yaml
icon_google_voice_search.png:
  name: Google Voice Search
  categories: ["Google", "V"]
  tags: ["microphone", "record", "voice", "sing", "sound"]
  mappings:
    - component: com.google.android.googlequicksearchbox/com.google.android.googlequicksearchbox.VoiceSearchActivity
```

This way, tags wouldn't pollute the XMLs but could still be used for search. Only really makes sense if everyone would adopt this or a similar format, though. It wouldn't be hard to build a bidirectional sync, where this file is created from an existing XML.
