### DISCUSSION TITLE
Crowdsourced Icon Mappings

### DISCUSSION THREAD

**Discussion by moertel** [zixpo/candybar#225] [Ideas]
I believe that Artic/Pacific is doing this with their paid service for icon requests but I firmly believe that XML mappings should be a crowdsourced centralised effort. In particular, I feel like I'm slowly going insane trying to map all HSBC bank app variants to the HSBC icon. :) Annoying for users having to waste icon requests for it, annoying for icon pack devs trying to "catch them all".

It would also significantly lower the barrier for new icon pack devs to get started because they can focus on drawing icons rather than updating XMLs. What are others' thoughts on this? Would this help you? I would strictly keep the centralised mapping to official app icons and system apps (flashlight, gallery, etc.)

**Comment by Donnnno** [comment]
Would be super helpful indeed.
I can recommend checking out Arcticons appfilter for now, I think it's the largest openly available appfilter out there:
https://github.com/Arcticons-Team/Arcticons/blob/main/newicons/appfilter.xml
We've also mapped many generic apps to generic icons:
https://docs.arcticons.com/contribute/updating-existing-apps#connect-generic-apps-to-existing-icons

And check out our open-source request dashboard here:
https://arcticons.com/requests

**Reply by moertel** [reply]
I love that you made the request dashboard public, that's really cool! Thanks as well for the offer to use the Arcticons mapping. :)

What would be a good way to offer this mapping (other than letting people manually copy bits and pieces)? With a tiny bit of GitHub magic, we might be able to use a bot for this who makes automatic PRs. Much like what Dependabot is doing for library updates, but for appfilter.

It might need a `.appfilterignore` file in each repo to make sure that discarded changesets are not suggested again. (I can imagine that some generic mappings like for banks and trading apps would yield some unwanted results).

**Reply by Donnnno** [reply]
Idk what the technical details should be, the icon dashboard is made by @Kaiserdragon2, maybe he has some nice ideas about a global appfilter.
Love the ambitious idea's btw!

**Reply by moertel** [reply]
@Kaiserdragon2, definitely curious how you think this would make sense for Arcticons. Maybe you already know how Dependabot or Renovate work. I'm imagining a similar approach where an icon pack developer can sign up with their icon pack repository (can also be private) via GitHub. The bot would run with GitHub resources on a specified schedule and then make a PR with new component+activity names.

The configuration could be done with a YAML file in the repository:
```yaml
# .iconpacker.yaml
sources:
  - url: https://github.com/Arcticons-Team/Arcticons/blob/main/app/src/main/res/xml/appfilter.xml
    priority: 1
  - url: https://somewhereelse/appfilter.xml
    priority: 2
  - url: https://yetanotherplace/appfilter.xml
    priority: 3
targets:
  - branch: main
    type: appfilter
    paths:
    - app/src/main/res/xml/appfilter.xml
    - app/src/main/assets/appfilter.xml
  - branch: main
    type: appmap
    paths:
    - app/src/main/res/xml
strategy: pr
schedule: "1st of each month" # could also be "every Monday"
quorum: 2 # would require that only components which exist in at least 2 of the sources are suggested
```

The logic could work like this:
 * Bot checks your appfilter.xml and sees that you have an icon called `gallery.png`
 * Bot sees that you've mapped `gallery.png` to `com.android.gallery.foo`
 * Bot sees that e.g. OtherIconPack has mapped `com.android.gallery.foo` and `com.android.gallery.bar` to `icon_picture_gallery.png`
 * Bot makes a PR on your repo to add `com.android.gallery.bar` mapped to `gallery.png`
 
 When there are incredibly generic icons, then a file such as this could help avoid false-positives:
 ```
 # .iconpackerignore
 bank.png
 weather.png
 ```
 (To avoid that all bank and weather apps get auto-mapped to a generic icon rather than a specific one.)
