### DISCUSSION TITLE
Create icon XML files from one central place

### DISCUSSION THREAD

**Discussion by moertel** [zixpo/candybar#68] [Ideas]
It happened to me a few times now that I wanted to add a new icon and forgot to update one of the 5 XML files in the repo. That led to very unnecessary bugs and it took me forever to debug.

I've since created a short and lightweight (Python) script that takes a central Yaml file with a mapping as input and generates all 5 required XML files (the ones currently included in the sample repo) from it. Is there any interest in including this in the candybar-sample repo? If so, I'd be happy to open a PR to add it. Otherwise, I could package the script into a tiny Docker container and we could refer to it from the docs.

The mapping looks like this, which I found to be the most versatile and allows per-component overrides of the names:

```yaml
icon_calendar.png:
  name: Calendar  # used in comments and as a fallback for individual components
  categories: ["C"]
  mappings:
  - component: com.samsung.android.calendar/com.samsung.android.app.calendar.activity.MainActivity
  - component: com.google.android.calendar/com.android.calendar.AllInOneActivity
    name: CalendarFoo  # component-specific override for the name
```

The categories used here need to match the ones defined in the Activity.
